# Generated by Django 3.2.4 on 2023-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=8, unique=True, verbose_name='UUID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('body', models.TextField(max_length=2000, verbose_name='Тело')),
                ('active', models.BooleanField(default=True, verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Лист заметок',
                'verbose_name_plural': 'Листы заметок',
            },
        ),
    ]
